# Generated by Django 5.0 on 2024-01-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(default=0)),
                ('userid', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('isdeleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('productid', models.IntegerField(default=0)),
                ('userid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('cartid', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('payment_mode', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='image')),
                ('discount', models.IntegerField(default=0)),
                ('categoryid', models.IntegerField(default=0)),
                ('sellerid', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('isdeleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.ImageField(default=0, upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('pincode', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=50)),
                ('isdeleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.ImageField(default=0, upload_to='')),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('pincode', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=50)),
                ('isdeleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(default=0)),
                ('userid', models.IntegerField(default=0)),
            ],
        ),
    ]
