# Generated by Django 5.0 on 2024-02-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_user_state_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sellerid',
            field=models.IntegerField(default=0),
        ),
    ]
