# Generated by Django 5.0 on 2024-03-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whishlist',
            new_name='wishlist',
        ),
    ]
