# Generated by Django 4.1.13 on 2024-04-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_whishlist_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='seller',
            new_name='sellerid',
        ),
    ]
