# Generated by Django 4.1.13 on 2024-04-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_seller_orders_sellerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellerid',
            new_name='seller',
        ),
    ]
