# Generated by Django 4.1.13 on 2024-04-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_orders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
