# Generated by Django 4.1.13 on 2024-04-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_orders_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='sellerid',
            new_name='seller',
        ),
    ]
