# Generated by Django 4.1.13 on 2024-04-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_sellerid_orders_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='sellerid',
        ),
    ]
