# Generated by Django 4.1.13 on 2024-04-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_seller_product_sellerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
    ]
