# Generated by Django 4.1.13 on 2024-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_rename_phone_num_contact_mobile_no_contact_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sellerid',
            field=models.IntegerField(default=0),
        ),
    ]
