# Generated by Django 4.1.13 on 2024-04-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_cart_sellerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sellerid',
        ),
    ]
