# Generated by Django 4.1.13 on 2024-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_cart_sellerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='categoryid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='sellerid',
            field=models.IntegerField(default=0),
        ),
    ]
