# Generated by Django 5.0.6 on 2024-06-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_remove_orders_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='seller',
            field=models.IntegerField(default=0),
        ),
    ]
